### ISSUE TITLE
Repeat key functionality issue

### ISSUE THREAD

**Issue by viquiram** [Iris0905/angular-onscreen-material-keyboard#11] opened 2020-01-23 11:31 UTC
This functionality does not work properly on touch devices. If you keep pressing a key for long enough,  the key is repeated forever.

**Comment by danielmoncada** [comment] 2020-01-23 16:15
@viquiram what type of browser / touch screen are you using?

**Comment by viquiram** [comment] 2020-01-23 18:03
@danielmoncada It's Embedded Linux with Chromium.

I haven't tested the keyboard on a smartphone but I'll try later.

**Comment by kenbash** [comment] 2020-01-23 18:19
Looking into this now

**Comment by kenbash** [comment] 2020-01-23 19:00
@viquiram Unfortunately, I was unable to reproduce this issue on our touch screens. Can you provide a video example or steps to reproduce?

I do have an idea of what could cause this, so I pushed up a quick fix to the branch _repeat-key-fix_. Try checking it out and let me know if the problem still occurs with that build.

**Comment by viquiram** [comment] 2020-01-23 20:56
@kenbash It looks like it's just happening in a particular situation.

I've also tried on my phone (chrome and firefox) and I couldn't reproduce the problem either. I even tested the demo on a surface and worked as expected.

Tomorrow, I will check your fix. Thanks.

**Comment by viquiram** [comment] 2020-01-24 11:13
Hi @kenbash 

I tested your fix and it didn't work. However, I think I know how to solve the issue.

When it happens, for some reason the keyboard dismisses before I stop pressing and reappears again. It means the 'pointerleave' and 'pointerup' events never get fired.

Therefore, calling 'cancelRepeat' in 'ngOnDestroy' should solve it.

**Comment by kenbash** [comment] 2020-01-24 23:13
Got it, we'll include that in the next release

**Comment by Iris0905** [comment] 2020-01-27 19:43
v0.3.1 is released with the fix

**Closed as completed** 2020-01-31 22:36 UTC
